---
title: "README"
output: github_document
---
### Overview
The following is a link to a running instance of the app: 
<https://iman-mir.shinyapps.io/iman_mir_flow_rate_extremes_app/>

This folder contains the app.R file with the shiny app functionalities, the rsconnect file containing the shinyapps.io information and the tests folder which tests the app usage.

The app contains multiple features including a drop-down search bar, slider, tabs, interactive table, panels, reactive expressions, renderPlot, renderText and renderUI functions among other features. 


### Description
The app contains multiple features to allow a user to determine the best coffee for them based on the coffee dataset.The app will suggest the highly recommended coffee and roaster location for the user, however the user can still look at the graphs and tables to see other options if they would like to. The user first chooses their country, their desired roast type and their price range. After clicking submit, on the coffee name recommendation tab the user will see the name(s) of their recommended coffee name based on the highest rating. There is also a graph which shows a visual of different coffees within the price range they chose, as well as a table with the corresponding information. The next tab shows the most highly recommended roaster of where they can buy different coffees from. There is also a corresponding table as well. The last tab is the customer reviews tab with a table with reviews for different coffees based on the preferences they chose. 